### ISSUE TITLE
doesn't work with Servlet API 2.5

### ISSUE THREAD

**Issue by yegor256** [yegor256/rexsl#42]
_migrated from Trac, where originally posted by **yegor256** on 30-Oct-2011 3:26pm_

This is what cloudbees is saying:

```
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getStatus()I
    com.rexsl.core.RestfulServlet.service(RestfulServlet.java:113)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    com.rexsl.core.XsltFilter.filter(XsltFilter.java:137)
    com.rexsl.core.XsltFilter.doFilter(XsltFilter.java:100)
```

We should work with 2.5 as well.
